# __NumPy Tutorial__


### Video: ___[Python NumPy Tutorial for Beginners](https://youtu.be/QUT1VHiLmmI)___

# Why Numpy?

- NumPy is faster:
    - Fixed type make data size smaller
    - Data stored in contiguous memory which operates faster

- NumPy applications:
    - Mathematics(Matlab replacement)
    - Backend(Pandas, Connect 4, Digital Photography)
    - Machine Learning

Install and Load


In [24]:
import numpy as np

## The Basics

In [25]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [26]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


Accessing/Changing specific elements, rows, columns, etc

In [27]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [28]:
# Get specific element [r, c]
a[1, 4]

10

In [29]:
# Get a specific row/column
print(a[1, :])
a[:, 3]

[ 6  7  8  9 10]


array([4, 9])

In [30]:
# [startindex:endindex:stepsize]
a[0,0:5:2]


array([1, 3, 5])

### The endindex is __EXCLUSIVE!__

$ 1+1*12321 $

`string`
> Text that will be indented when the Markdown is rendered.

laksdjf
- Main bullet point
     - Sub bullet point
     
1. Numbered item
1. Numbered item

<div class="alert alert-block alert-info">
<b>Tip:</b> Use blue boxes (alert-info) for tips and notes. 
If it’s a note, you don’t have to include the word “Note”.
</div>

<div class="alert alert-block alert-warning">
<b>Example:</b> Use yellow boxes for examples that are not 
inside code cells, or use for mathematical formulas if needed.
</div>

<div class="alert alert-block alert-success">
<b>Up to you:</b> Use green boxes sparingly, and only for some specific 
purpose that the other boxes can't cover. For example, if you have a lot 
of related content to link to, maybe you decide to use green boxes for 
related links from each section of a notebook.
</div>

<img src=“https://en.wikipedia.org/wiki/Project_Jupyter#/media/File:Jupyter_logo.svg” alt=“Alt text” title=“Title text” />

&#9651

***

[Section title](#section-title)